databases:
  - name: resume-analyzer-db
    databaseName: resume_analyzer_db
    user: resume_user
    plan: free

services:
  - type: web
    name: ai-resume-analyzer
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn resume_analyzer_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString